const colorscustomiser = [
  {
    colors: [
      "#F4F6EF",
      "#F9F1DF",
      "#B50024",
      "#127048",
      "#008FD2",
      "#34394B",
      "#9A9B9D",
      "#44312E",
      "#221E1F",
    ],
    type: ["lf_quarter_lateral", "rt_quarter_lateral"],
    title: "Outside Body",
    show: true,
  },
  {
    colors: [
      "#F4F6EF",
      "#F9F1DF",
      "#B50024",
      "#127048",
      "#008FD2",
      "#34394B",
      "#9A9B9D",
      "#44312E",
      "#221E1F",
    ],
    type: ["lf_quarter_medial", "rt_quarter_medial"],
    title: "Inside Body",
    show: true,
  },
  {
    colors: [
      "#F4F6EF",
      "#F9F1DF",
      "#B50024",
      "#127048",
      "#008FD2",
      "#34394B",
      "#9A9B9D",
      "#44312E",
      "#221E1F",
    ],
    type: ["lf_toe_cap", "rt_toe_cap"],
    title: "Tongue",
    show: false,
  },
  {
    colors: [
      "#F4F6EF",
      "#F9F1DF",
      "#B50024",
      "#127048",
      "#008FD2",
      "#34394B",
      "#9A9B9D",
      "#44312E",
      "#221E1F",
    ],
    type: ["lf_heel_stay", "rt_heel_stay"],
    title: "Heal Stripe",
    show: false,
  },
  {
    colors: [
      "#F4F6EF",
      "#F9F1DF",
      "#B50024",
      "#127048",
      "#008FD2",
      "#34394B",
      "#9A9B9D",
      "#44312E",
      "#221E1F",
    ],
    type: ["lf_liner_medial", "rt_liner_medial"],
    title: "Lining",
    show: false,
  },
  {
    colors: [
      "#F4F6EF",
      "#F9F1DF",
      "#B50024",
      "#127048",
      "#008FD2",
      "#34394B",
      "#9A9B9D",
      "#44312E",
      "#221E1F",
    ],
    type: [
      "lf_stiches_tongue",
      "lf_stitches_heel_stay",
      "lf_stitches_inner_counter_binding",
      "lf_stitches_lace_loop",
      "lf_stitches_lateral_outer",
      "lf_stitches_medial_outer_collar",
      "lf_stitches_quarter_lateral_liner",
      "lf_stitches_quarter_medial_liner",
      "rt_stitches_tongue_label",
      "rt_stiches_tongue",
      "rt_stitches_heel_stay",
      "rt_stitches_inner_counter_binding",
      "rt_stitches_lace_loop",
      "rt_stitches_lateral_outer",
      "rt_stitches_medial_outer_collar",
      "rt_stitches_quarter_lateral_liner",
      "rt_stitches_quarter_medial_liner",
      "rt_stitches_tongue_label",
    ],
    title: "Stitch",
    show: true,
  },
  {
    colors: [
      "#F4F6EF",
      "#F9F1DF",
      "#B50024",
      "#127048",
      "#008FD2",
      "#34394B",
      "#9A9B9D",
      "#44312E",
      "#221E1F",
    ],
    type: ["lf_lace_a", "lf_lace_b", "rt_lace_a", "rt_lace_b"],
    title: "Laces",
    show: true,
  },
  {
    colors: [
      "#F4F6EF",
      "#F9F1DF",
      "#B50024",
      "#127048",
      "#008FD2",
      "#34394B",
      "#9A9B9D",
      "#44312E",
      "#221E1F",
    ],
    type: [
      "lf_midsole_tape_a",
      "lf_midsole_tape_b",
      "lf_midsole_tape_c",
      "rt_midsole_tape_a",
      "rt_midsole_tape_b",
      "rt_midsole_tape_c",
    ],
    title: "Rubber",
    show: true,
  },
  {
    colors: [
      "#F4F6EF",
      "#F9F1DF",
      "#B50024",
      "#127048",
      "#008FD2",
      "#34394B",
      "#9A9B9D",
      "#44312E",
      "#221E1F",
    ],
    stripe: {},
    type: [
      "lf_midsole_pinstripe",
      "lf_midsole_topline",
      "rt_midsole_pinstripe",
      "rt_midsole_topline",
    ],
    title: "Racing Stripe",
    show: true,
  },
];

export default colorscustomiser;
